.travis.yml
The last 0.8 update was over two years ago. Getting with the times.
Many tests fail in 4.0+ because ES6 is the new black.
=> Update travis-ci Node versions

.gitignore, README.md, gulpfile.js, package.json, package.json5
Reverting because gulp-browserify doesn't support the standalone option, which we need. The Browserify portions of #89 may be implemented instead.
=> Revert "Browserify"

README.md, package.json, package.json5
Mocha 2 dropped support for Node v0.4 and v0.6.
=> Upgrade mocha

lib/json5.js, test/count-newlines.js, test/parse-cases/arrays/no-comma-array.errorSpec, test/parse-cases/comments/top-level-block-comment.errorSpec, test/parse-cases/comments/top-level-block-comment.txt, test/parse-cases/comments/top-level-inline-comment.errorSpec, test/parse-cases/comments/top-level-inline-comment.txt, test/parse-cases/objects/illegal-unquoted-key-number.errorSpec, test/parse-cases/objects/illegal-unquoted-key-symbol.errorSpec, test/parse-cases/objects/leading-comma-object.errorSpec, test/parse-cases/strings/no-comma-array.errorSpec, test/parse-cases/strings/unescaped-multi-line-string.errorSpec, test/parse.js, test/require.js, test/stringify.js
Hi - here is my proposed fix for #86 introducing support for line and column numbers.
I've introduced a new "errorSpec" system which allows us to write little JSON5 files with the "errorSpec" suffix alongside parse fail ".txt" files holding assertions about the error contents - this will allow us to write tests for #69 easily if we want to address it later.
I'm sorry I had to subvert the "exports" style for mocha slightly since it didn't sit nicely with the dynamism relating to whether we have an errorSpec file or not - I could try harder to preserve it, but I think it might be a little messy either way.
Thanks for any feedback!
=> Add support for line and column number context for errors: #86

package.json
```
$ tree node_modules/json5 -I node_modules -L 3
node_modules/json5
├── lib/
│   ├── cli.js*
│   ├── json5.js
│   └── require.js
├── test/
│   ├── parse-cases/
│   │   ├── arrays/
│   │   ├── comments/
│   │   ├── misc/
│   │   ├── new-lines/
│   │   ├── numbers/
│   │   ├── objects/
│   │   ├── strings/
│   │   └── todo/
│   ├── parse.js
│   ├── readme.md
│   ├── require.js
│   └── stringify.js
├── .editorconfig
├── .npmignore
├── .travis.yml
├── CHANGELOG.md
├── README.md
├── package.json
└── package.json5
```
Loading unnecessary files is one of the reasons `npm install`s take so darn long. Anton Rudeshko very well put it in [his article](http://www.rudeshko.com/web/2014/05/13/help-people-consume-your-npm-packages.html):
> Speaking in terms of object-oriented design, your npm package …
=> include only necessary files in npm package

package.json, package.json5
Without this, npm v3 will not install jshint along with gulp-jshint.
=> Explicitly declare peer dependency jshint

README.md
Currently the link to package.json5 on [json5.org](http://json5.org/#example) is broken. This change ensures the package.json5 link works when the readme is served on either github or json5.org
=> make package.json5 link in readme a full url

index.md
[RFC 7159](https://tools.ietf.org/html/rfc7159) is obsoleted by [RFC 8259](https://tools.ietf.org/html/rfc8259).
=> Latest RFC about JSON

package.json
This PR allows bundlers like `webpack`, `rollup` and `parcel` to take advantage of the es-module build.
=> Add module entry to package.json

lib/stringify.js, test/stringify.js
The following is invalid JSON5 and ES5 because a digit cannot follow a
null character escape.
'\01'
However, JSON5 stringifies `'\x001'` as `'\01'` making it impossible to
round trip. This commit ensures that JSON5 stringifies null characters
as `\x00` when followed by a digit.
=> fix: stringify `\0` as `\\x00` in some cases

package-lock.json, package.json
The version of minimist used in the project contains a vulnerability fixed in the newer version.
https://app.snyk.io/test/npm/minimist/1.2.0
This change updates the dependency.
=> minimist library updated to the latest version (1.2.5)

lib/util.js, test/parse.js
When parsing a bare hexadecimal number like `JSON5.parse('0x1')`, the parser was looping forever [here](https://github.com/json5/json5/blob/v2.1.2/lib/parse.js#L540-L543) because it was reading to the end and `util.isHexDigit(undefined) === true`.
I updated all of the `util.is*` functions to return `false` for `undefined` and added some regression tests.
Fixes #228.
=> Fix OOM when parsing bare hexadecimal literal.

CHANGELOG.md, lib/cli.js, package-lock.json, package.json, test/cli.js
Fixes #266, #205
Closes #242, #222
=> fix: remove minimist

README.md
As the Node world is shifting to ESM imports, it's time to shift instructions in that direction, as well as nudge more people toward ESM ;)
=> Add ESM usage to README

README.md
Aims to fix #285:
* Explain JSON5 better. Proactively emphasize that this is for config file type use cases, not machine-to-machine communication (the `#1` misunderstanding or objection to JSON5).
* Market/sell it better. The stats and company/project names are exciting! =)
* Link to blog post. This doesn't need to be front-and-center though; just added it to my name in the credits.
* Emphasize ES5 compatibility. Just put a stake in the ground here and preempt feature requests we'll never accept.
=> Improve readme (e.g. explain JSON5 better!)

CHANGELOG.md, lib/parse.js, test/parse.js
=> Add __proto__ to objects and arrays

.github/issue_template.md, .github/pull_request_template.md, README.md, SECURITY.md
This PR publishes a security policy for reporting vulnerabilities as well as linking to it from the README and GitHub issue and pull request templates.
Also fixes a minor typo in the GitHub issue template.
=> Publish a security policy

CHANGELOG.md, src/parse.js, test/parse.js
According to npm, [`1.0.1` has more downloads](https://www.npmjs.com/package/json5?activeTab=versions) so it makes sense to backport it.
=> Backport fix for CVE-2022-46175 to v1

README.md
This PR adds the following section to the readme to explain why JSON and JSON5 are not strict subsets of ES5 yet they are strict subsets of ES2019.
> ## ECMAScript Compatibility
>
> While JSON5 aims to be fully compatible with ES5, there is one exception where both JSON and JSON5 are not. Both JSON and JSON5 allow unescaped line and paragraph separator characters (U+2028 and U+2029) in strings, however ES5 does not. A [proposal](https://github.com/tc39/proposal-json-superset) to allow these characters in strings was adopted into ES2019, making JSON and JSON5 fully compatible with ES2019.
Links to this section have been added to appropriate places in the readme as footnotes.
The wording as also been changed to say that JSON5 is just a subset of ES5 but not a _strict_ subset.
=> Explain ECMAScript compatibility

package-lock.json, package.json
bump minimize to 1.2.6 to fix [CVE-2021-44906](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795)
[tsconfig-paths](https://github.com/dividab/tsconfig-paths) v3 version is still using v1 version of json5
=> build: update minimist to 1.2.8
